import { Component, OnInit } from '@angular/core';
import { CrudService } from '../crud.service';

@Component({
  selector: 'app-musica',
  templateUrl: './musica.component.html',
  styleUrls: ['./musica.component.css']
})
export class MusicaComponent implements OnInit {
  musicas: any[]= [
    { b:"Ministério Morada",q:"44"},  
    { b:"Isaías Saad",q:"26"},  
    { b:"Gabriela Rocha",q:"22"},  
    { b:"Corinhos Evangélicos",q:"263"},  
    { b:"Diante do Trono",q:"335"},  
    { b:"Ministério Zoe",q:"79"},  
    { b:"Casa Worship",q:"10"},  
    { b:"Ministerio Voz de Muitas Águas",q:"39"},  
    { b:"Raiz Coral",q:"35"},  
    { b:"Novo Som",q:"101"},  
    { b:"Alda Célia",q:"85"},  
    { b:"Cristina Mel",q:"157"},  
    { b:"João Alexandre",q:"94"},  
    { b:"Banda Dom",q:"49"},  
    { b:"Ana Paula Valadão",q:"39"},  
    { b:"Bola de Neve",q:"78"},  
    { b:"André e Felipe",q:"71"},  
    { b:"Armando Filho",q:"41"},  
    { b:"Judson Oliveira",q:"58"},  
    { b:"Marcos Góes",q:"73"},  
    { b:"Chris Durán",q:"3"},  
    { b:"Fruto Sagrado",q:"54"},  
    { b:"Ozéias de Paula",q:"114"},  
    { b:"Jesus Culture",q:"119"},  
    { b:"Fonte da Vida",q:"33"},  
    { b:"Clamor Pelas Nações",q:"75"},  
    { b:"Santa Geração",q:"133"},  
    { b:"Daniel Ludtke",q:"84"},  
    { b:"Ronaldo Bezerra",q:"50"},  
    { b:"Ouvir e Crer",q:"268"},  
    { b:"Marcela Taís",q:"30"},  
    { b:"Kelly Patrícia",q:"116"},  
    { b:"Skillet",q:"159"},  
    { b:"Hillsong Music Australia",q:"213"},  
    { b:"Grupo Logos",q:"69"},  
    { b:"Ministério Cristo Vivo",q:"25"},  
    { b:"Davi Fernandes",q:"62"},  
    { b:"Comunidade Evangélica de Maringá",q:"68"},  
    { b:"Elaine Martins",q:"49"},  
    { b:"Elaine de Jesus",q:"86"},  
    { b:"Bethel Church",q:"45"},  
    { b:"Ministério Além do Véu",q:"34"},  
    { b:"Ao Cubo",q:"11"},  
    { b:"Katsbarnea",q:"40"},  
    { b:"Hillsong Worship",q:"72"},
    { b:"Casting Crowns",q:"90"},  
    { b:"Coral Resgate",q:"30"},  
    { b:"Denise Cerqueira",q:"7"},  
    { b:"Kadoshi",q:"27"},  
    { b:"Apocalipse 16",q:"9"},  
    { b:"Atmosfera De Adoração",q:"34"},  
    { b:"Pregador Luo",q:"13"},  
    { b:"Grupo Elo",q:"40"},  
    { b:"Dany Grace",q:"35"},  
    { b:"Fernanda Lara",q:"31"},  
    { b:"Igreja Bíblica da Paz",q:"47"},  
    { b:"Brother Simion",q:"75"},  
    { b:"Brás Adoração",q:"24"},  
    { b:"Altos Louvores",q:"30"},  
    { b:"R.R. Soares",q:"42"},  
    { b:"Ministério Hebrom",q:"19"},  
    { b:"Rodolfo Abrantes",q:"58"},  
    { b:"Antônio Cirilo",q:"64"},  
    { b:"Nívea Soares",q:"102"},  
    { b:"Preto No Branco",q:"43"},  
    { b:"Isadora Pompeo",q:"32"},  
    { b:"Midian Lima",q:"18"},  
    { b:"Laura Souguellis",q:"26"},  
    { b:"Fernandinho",q:"160"},  
    { b:"Anderson Freire",q:"101"},  
    { b:"Gabriel Guedes",q:"65"},  
    { b:"Alessandro Vilas Boas",q:"32"},  
    { b:"Kemuel",q:"67"},  
    { b:"Ministério Apascentar de Louvor (Toque No Altar)",q:"109"},  
    { b:"Rosa de Saron",q:"146"},  
    { b:"Fernanda Brum",q:"193"},{ b:"Davi Sacer",q:"109"},  
    { b:"Eli Soares",q:"59"},  
    { b:"Luma Elpidio",q:"26"},{ b:"Soraya Moraes",q:"89"},  
    { b:"Kleber Lucas",q:"116"},  
    { b:"David Quinlan",q:"111"},  
    { b:"Leonardo Gonçalves",q:"71"},  
    { b:"Bruna Karla",q:"106"},  
    { b:"Paulo César Baruk",q:"120"},  
    { b:"Ministério Avivah",q:"30"}, { b:"Adhemar de Campos",q:"101"},  
    { b:"Renascer Praise",q:"236"},  
    { b:"Oficina G3",q:"89"},  
    { b:"Israel Subirá",q:"7"},  
    { b:"Trazendo a Arca",q:"88"},  
    { b:"Quatro Por Um",q:"106"},  
    { b:"Eyshila",q:"124"},  
    { b:"Gerson Rufino",q:"136"},  
    { b:"Delino Marçal",q:"24"},  
    { b:"Livres Para Adorar",q:"63"},  
    { b:"Priscilla Alcantara",q:"55"},  
    { b:"Heloísa Rosa",q:"80"},  
    { b:"Shirley Carvalhaes",q:"172"},  
    { b:"Catedral",q:"213"},  
    { b:"Anjos de Resgate",q:"89"},  
    { b:"Samuel Mariano",q:"72"},  
    { b:"Vineyard",q:"107"},  
    { b:"Irmão Lázaro",q:"66"},  
    { b:"Sérgio Lopes",q:"188"},  
    { b:"Hillsong United",q:"389"},
    { b:"Casa Worship",q:"10"},  
    { b:"Walmir Alencar",q:"73"},  
    { b:"Padre Zezinho",q:"343"},
      { b:"André Valadão",q:"147"},  
    { b:"Cassiane",q:"168"},
      { b:"Voz da Verdade",q:"329"},  
    { b:"Frei Gilson",q:"37"},  
    { b:"Pedras Vivas",q:"47"},  
    { b:"Sarah Farias",q:"28"},  
    { b:"Damares",q:"88"},  
    { b:"Vida Reluz",q:"105"},  
    { b:"Eliana Ribeiro",q:"85"},  
    { b:"Pr. Lucas",q:"62"},  
    { b:"Regis Danese",q:"88"},  
    { b:"André Aquino",q:"26"},  
    { b:"Ludmila Ferber",q:"165"},  
    { b:"Asaph Borba",q:"180"},  
    { b:"Lauriete",q:"117"},  
    { b:"Missionário Shalom",q:"110"},  
    { b:"Leandro Borges",q:"36"},  
    { b:"Marquinhos Gomes",q:"62"},  
    { b:"PG",q:"89"},  
    { b:"Jotta A",q:"49"},
      { b:"Marcos Antonio",q:"109"},  
    { b:"Mara Lima",q:"93"},  
    { b:"Discopraise",q:"47"},  
    { b:"Comunidade de Nilópolis",q:"52"},  
    { b:"Mariana Valadão",q:"45"},  
    { b:"Deigma Marques",q:"50"},  
    { b:"Rose Nascimento",q:"110"}, 
    { b:"Ministerio Amor e Adoração",q:"44"},  
    { b:"Ministério Ipiranga",q:"72"},
      { b:"Padre Zeca",q:"41"},  
    { b:"Khorus",q:"63"},  
    { b:"Ministério Sarando a Terra Ferida",q:"72"},  
    { b:"Igreja Cristã Maranata",q:"277"},  
    { b:"Daniela Araújo",q:"75"},  
    { b:"Jamily",q:"48"},  
    { b:"Casa de Davi",q:"83"},  
    { b:"Celina Borges",q:"73"},  
    { b:"Mattos Nascimento",q:"108"},  
    { b:"Ministério Jovem",q:"166"},  
    { b:"Ana Nóbrega",q:"32"},  
    { b:"Giselli Cristina",q:"46"},
      { b:"J. Neto",q:"102"},
      { b:"Vencedores Por Cristo",q:"237"}
    
    ]
 

  constructor() { }

  ngOnInit() {
  
  }

}
